version: 2
jobs:
  build:
    working_directory: ~/app/PixelMCShowdownAPI
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    environment:
      APP_NAME: "pixelmcshowdownapi"
    steps:
      - checkout:
          path: ~/app
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/$APP_NAME.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=$APP_NAME -t $APP_NAME .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/$APP_NAME.tar $APP_NAME
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/$APP_NAME.tar
      - run:
          name: Run tests
          command: |
            docker-compose -f ./docker-compose.test.yml up
      - deploy:
          name: Save Image
          command: |
            mkdir drop
            docker save "$APP_NAME":latest | gzip > drop/drop.tgz
      - store_artifacts:
          path:  ./drop 

workflows:
    version: 2
    build:
      jobs:
        - build